# Example file of custom_key.toml. Rename to custom_key.toml while using.
[KEY_LIST]
# Perform a full component scan and registration for all the paths under this list.
#example_key = 'AnExampleKey'

# models
# dashscope llm model: qwen_llm
#DASHSCOPE_API_KEY = 'sk-xxxxxx'

#kimi default name: default_kimi_llm
#KIMI_API_KEY=''
#
##Qwen default name: default_qwen_llm
#
##Opean default name: default_openai_llm
#OPENAI_API_KEY='sk-xxxxxx'
#
##DEEPSEEK default name: default_deepseek_llm
#DEEPSEEK_API_KEY=''
#DEEPSEEK_API_BASE=''
#
## WenXin default name: default_wenxin_llm
#QIANFAN_AK=''
#QIANFAN_SK=''
#
##Ollama default name: default_ollama_llm
#OLLAMA_BASE_URL=''
#
##claude default name: default_claude_llm
#ANTHROPIC_API_KEY=''
#ANTHROPIC_API_URL='xxxxxx'
#
##baichuan default name: default_baichuan_llm
#BAICHUAN_API_KEY='xxxxxx'


# search
#Google search
#SERPER_API_KEY=''
#
##search api
#SEARCHAPI_API_KEY = ''
#
##bing seacrh
#BING_SUBSCRIPTION_KEY='xxxxxx'